OUTDIR: ./ # specify output directory, ending with '/'
DEFAULT_CNA: 2
E: .01
SITE_COVERAGE_THRESHOLD: .66
CELL_COVERAGE_THRESHOLD: .66
STATUS_CONFIDENCE_THRESHOLD: 1 
P00: .33
P10: .33
P11: .33
P: .5
D0010: .5
D0011: 1
D1011: .5
ALGO: N # (F)astME v.s. (N)eighbor-joining
MAX_ITER: 40
KAPPA: .1
PARTITION_VALIDITY_THRESHOLD: .5
MINIMUM_SUBTREE_SIZE: .05

PATIENTS:
    CRC01: 
        methylated_rc: data/CRC01_methylated_read_counts.npz
        unmethylated_rc: data/CRC01_unmethylated_read_counts.npz
        cna: data/CRC01_CNA_calls.npz
        whitelist: data/CRC01_whitelist.txt
        root: NC_507
        labels: data/CRC01_labels.csv
        palette:
            lesion:
                NC: "#A7A7A7"
                LN: "#EF8432"
                PT: "#487DB2"
                ML: "#D1342B"
                MP: "#68AC57"
            sampling_location:
                NC: "#A7A7A7"
                LN1: "#F8CA98"
                LN2: "#F38419"
                PT1: "#AFD1F2"
                PT2: "#739CC5"
                PT3: "#42719F"
                PT4: "#205183"
                ML1: "#E8A9A8"
                ML2: "#CC3426"
                ML3: "#B94C47"
                ML4: "#89221B"
                MP1: "#DBF7D4"
                MP2: "#9EF185"
                MP3: "#4FB31A"
                MP4: "#489C22"
                MP5: "#32780D"
